export const defaultUrl = "http://138.68.159.26:3400";
export const DECRYPTIONKEY =
  "ZWpocnF3Z2xxdWZsZ2ZoHWHJHBBJWFBEWOOWEIOWJROJWOKJWJKWSKcnJrci5xZWxyZLNSNDSDJBSLSKEWHEJWLWLWLLWJEJBWVVJEWVJWJBJWJBEJWEHWEHWKLHDSLDSSSDNFDKSBKJKJRWBRJRWeXd5d3l3eXd5eXd5d3l5eX";
export const NAIRA_SIGN = "\u20A6";
